### ISSUE TITLE
How to specify rootElement ?

### ISSUE THREAD

**Issue by antulik** [xcambar/ember-cli-embedded#1]
How do I pass rootElement configuration to embedded app?

**Comment by xcambar** [comment]
Do as with any Ember app; in `config/environment`, add:
`ENV.APP.rootElement = '#my-root-element';`

See http://emberjs.com/api/classes/Ember.Application.html#property_rootElement, an example lies at the top of the page.

**Comment by antulik** [comment]
Sorry I wasn't very clear with my question. 

How do I pass rootElement configuration to embedded app dynamically from outside of ember app? 

as a work-around i've set `rootElement` to the class, and append that class to the target element. But wondering is there a better approach.

**Comment by xcambar** [comment]
Aaah, ok! I'll look into it.

This is interesting and it sounds like a pretty common use case. More on that pretty soon, hopefully.
