### ISSUE TITLE
Configuration api is not suitable for use

### ISSUE THREAD

**Issue by antulik** [xcambar/ember-cli-embedded#2]
The problem we have with passing configuration to ember-cli-embedded is that all code references have to be changed which access `config/environment.js`.

```js
const embeddedConfig = container.lookup('config:embedded');
```

 The problem is that `config:embedded` is only available when `ember-cli-embedded` is enabled, meaning it can't be environment specific. 

We've ended up doing plain ember approach:

```js
GlobalAppVar.__container__.lookupFactory('config:environment').APP.host = 'example.com'
```

Advantages
- app does not depend on ember-cli-embedded 
- no code changes required for embedded mode

Issues
- not all config will reflect changes (e.g. rootElement does not work)

What are the advantages of introducing new configuration system with `ember-cli-embedded` rather than using existing one?

**Comment by xcambar** [comment]
> What are the advantages of introducing new configuration system with ember-cli-embedded rather than using existing one?

Avoiding configuration collision was my first thought. But if what you want _is_ to merge external and internal configuration, then obviously it defeats the point.

Good point on the `config:embedded` not being always available.

I've created #4 as the target for the related enhancement, feel free to comment.

**Comment by antulik** [comment]
i guess we'll move discussion to #4
